# Generated by Django 3.2.16 on 2022-12-09 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Patient Name')),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150, verbose_name='Country Name')),
                ('state', models.CharField(max_length=150, verbose_name='State Name')),
                ('district', models.CharField(max_length=150, verbose_name='District Name')),
                ('street', models.CharField(max_length=150, verbose_name='Street Name/Number')),
                ('place_number', models.SmallIntegerField(verbose_name='Place Number')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_address', to='hospital.patientmodel', unique=True, verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionals_name', models.CharField(max_length=150, verbose_name="Professional's Name")),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('weight', models.FloatField(verbose_name='Patient Weight')),
                ('height', models.FloatField(verbose_name='Patient Height')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='hospital.patientmodel', verbose_name='Patient')),
            ],
        ),
    ]
