# Generated by Django 3.2.16 on 2022-12-09 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Patient Name')),
                ('age', models.SmallIntegerField(verbose_name='Patient Age')),
                ('address', models.CharField(max_length=255, verbose_name='Patient Address')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionals_name', models.CharField(max_length=150, verbose_name="Professional's Name")),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('weight', models.FloatField(verbose_name='Patient Weight')),
                ('height', models.FloatField(verbose_name='Patient Height')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='hospital.patientmodel', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
            },
        ),
    ]
